import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import Image from "next/image"; // ✅ Correct import for Next.js Image component
import { GlobalStateProvider } from "../hooks/globalHook";

export const metadata = {
  title: "store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  

  
  return (
    <GlobalStateProvider>
    <html lang="ar">
      
      <body className="h-screen bg-gradient-to-br from-orange-400 via-orange-100 to-orange-50">
        {/* <nav className="bg-white shadow-md py-4 px-6 fixed w-screen" dir="rtl">
          <div className="container mx-auto flex flex-row justify-between items-center">
            <div className="flex justify-center items-center flex-row">
             
              <Image 
                src={"/Pictogrammers-Material-Warehouse.svg"} 
                alt="Logo" 
                width={50} 
                height={50} 
                priority 
              />
              <p
                className="text-xl font-bold"
                style={{ color: "lab(32 -1.69 -39.12)" }}
              >
                <span className="text-orange-400"></span>
              </p>
            </div>

            <div>
               <p
                className="text-xl font-bold "
                style={{ color: "lab(32 -1.69 -39.12)" }}
              >Ware
                <span className="text-orange-400">house </span>
                <span className="text-black"> System</span>
              </p>
            </div>
          </div>
        </nav> */}

        {children}
        
      </body>
 
    </html>
    </GlobalStateProvider>
  );
}
